# Generated by Django 4.0.6 on 2022-07-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
